### ISSUE TITLE
Multiple Locations

### ISSUE THREAD

**Issue by robneu** [NateWr/business-profile#6]
Do you have any plans to add support for multiple locations? Would you be interested in a pull request to add them?

**Comment by NateWr** [comment]
Thanks and yes, @robneu! The two priorities for me are a) to preserve seamless backwards compatibility and b) to ensure that the plugin stays simple and streamlined for most use-cases (ie - single location). Here's what I envision for a basic, first-pass approach to multiple locations.

1. The existing settings, which are stored in wp_options, remain as the "overall" business profile (like the HQ or main office or whatever).

2. A new setting is added which allows people to "toggle" multiple locations on/off. It's off by default.

3. When on, new menu pages appear under Business Profile called "Locations" and "Add Location". These would be an interface for a custom post type and a WP_List_Table implementation.

4. The Add/Edit Location page would be highly stripped down to just include the bare necessities. Basically, all of the settings under Business Profile.

5. The `[contact-card]` shortcode can be extended to include a `location` argument, which accepts a location post type `ID`.

This would work as an initial implementation and preserve the existing setup without disrupting anyone's custom implementations. Later we can talk about if we need to add taxonomies. What kind of front-end searching/interfaces we want to add, etc.

In terms of the data structure and code, I'd like to see the following:

1. Since I built this plugin as part of a suite of restaurant plugins for my business, I'd like to see it follow the code design patterns set out in those plugins. Particularly, [Restaurant Reservations](https://github.com/NateWr/restaurant-reservations/). That means putting custom post type declarations and post metaboxes into a [CustomPostTypes.class.php](https://github.com/NateWr/restaurant-reservations/blob/master/includes/CustomPostTypes.class.php) file and, if needed, extending the [WP_List_Table](https://github.com/NateWr/restaurant-reservations/blob/master/includes/WP_List_Table.BookingsTable.class.php) class.

2. Should we liaise or consult with the [Custom Post Type standards project](https://github.com/justintadlock/content-type-standards) led by Justin Tadlock? Currently no one has opened discussion on a Locations type, but where possible it'd be nice to use some common naming practices they've designed.

Regarding #1, I'm happy to scaffold the new Custom Post Type and add the locations on/off toggle to the Business Profile page (it might take you a while to wrap your head around my [Simple Admin Pages](https://github.com/NateWr/simple-admin-pages) library that is being used). You could then jump in and tweak the post meta, work on the adjustments for the shortcode implementation, or anything else.

FYI, I'm going to be pretty absent this weekend as I have a visitor arriving. But let me know what you think, or any other ideas, and we can move forward on this. In general,  I'd prefer to spin off tasks into smaller, bite-size chunks for PRs.

**Comment by NateWr** [comment]
I've opened up a discussion on content standards [here](https://github.com/justintadlock/content-type-standards/issues/25).

**Comment by NateWr** [comment]
Hi @robneu, I suggest we go ahead and move forward on this. I don't expect the content standards issues will be sorted out any time soon, and we've got at least some basics in place (and clarified some important things re: lat/lon). The only really tricky question we have left is with the opening hours.

I'm open to hearing otherwise. But I'm in favor of serializing them *for now* in the same structure in which they are stored for the single profile. I can definitely see a future where someone might want to query something like: the nearest location that is open right now. In that case, we'd need to have the opening hours more easily queryable.

But I think if I'm honest I'd rather bump that issue down the road and maybe even leave it for advanced implementations (possibly custom tables). The idea of having a ton of `_location_opening_hours_monday_open` post meta values for every location feels like it could quickly pollute the database with thousands of extra rows. And it would be really easy to build a custom database table implementation *later* if we decided that such a feature was important.

Thoughts? Are you still up for working on this some? If so I'll start scaffolding the post type.

**Comment by robneu** [comment]
That all sounds fine to me. Storing the opening hours as a single value is probably the best way to do it.

 One thing that I think might be handy would be to include support for the editor on the post type so people can include additional information about each location if they would like to. That would probably address some of the issues raised on the content standards thread such as the location description and anything else people might want to include.

It's also pretty important from an SEO standpoint that each location has some amount of unique text-based content on it if they're trying to use them for any kind of local SEO purposes.

**Comment by NateWr** [comment]
Agreed.

**Comment by robneu** [comment]
Also, I'm not sure if you already have an internal solution for plugin template loading, but if not I suggest just pulling in https://github.com/GaryJones/Gamajo-Template-Loader as a dependency.

One drawback is that it doesn't allow data to be passed into the template. If we need to do that, a modified version exists here: https://github.com/audiotheme/cue/blob/develop/includes/class-cue-template-loader.php

**Comment by NateWr** [comment]
Currently the plugin uses a [filtered array of callbacks](https://github.com/NateWr/business-profile/blob/master/includes/template-functions.php#L58-L71) to print the contact card components. I've had a lot of success with this approach with the booking form in my Restaurant Reservations plugin, though I'm open to considering alternatives.

The callback array is nice for more granular control over elements and easy use of context. It also helps encapsulate a lot of logic which would be confusing in a template (like [formatting the opening h ours](https://github.com/NateWr/business-profile/blob/master/includes/template-functions.php#L199-L405)). But I appreciate that people are accustomed to templates, especially if we're moving into more traditional post type behaviour. If we do switch over we'll need to be careful about how we manage  backwards compatibility.

I'm hesitant to add a dependency for something as simple as template loading, to be honest, but would be happy to model a solution on Gary's work there. I'd just prefer to understand and implement the code rather than pull it in as a `lib`, which can lead to namespace clashes with other plugins that might be using the base class as well.

**Comment by robneu** [comment]
I like the filtered callback approach. I think it would be fine to combine the two into a single approach and use those callbacks as template tags within a template. Basically, just load a template within your callback function instead of outputting HTML directly within it.

It's not a huge deal really, but it can make loading custom versions of the data pretty straightforward within a theme or child theme.

**Comment by NateWr** [comment]
The [actual template](https://github.com/NateWr/business-profile/blob/master/includes/template-functions.php#L69-L71) will be tiny, but I think you're right that it's a good idea. Let's move forward on the CPTs first and set up the template loading once we're updating the `[contact-card]` shortcode for that. I'd like to cascade through a context as well, so that people can use something like `bpfwp_get_template( 'contact-card', 'list' );` and `bpfwp_get_template( 'contact-card', 'single' );` to load unique `*-list.php` and `*-single.php` templates, and even set up their own custom ones (perhaps the widget could look for a `*-widget.php` template).

I'll try to organize our thoughts here into a series of issues so we can start work.

**Comment by NateWr** [comment]
@robneu The basic architecture for the custom post type is in place (see #7). There should be a lot of little tasks to do so feel free to jump in on anything you want to work on. Thanks!

**Comment by NateWr** [comment]
Closing this for now as all considerations are in other issues. Feel free to create issues with new feature requests/bugs related to the multiple locations.
