### ISSUE TITLE
Handle new Google requirement for image

### ISSUE THREAD

**Issue by NateWr** [NateWr/business-profile#61]
Google now seems to expect an `image` object for `FoodEstablishment` types. Maybe for all `LocalBusiness` types.

https://search.google.com/structured-data/testing-tool/u/0/#url=demo.themeofthecrop.com%2Fluigi

Research what's behind this new requirement and add an ability to support this.

We may be able to pull an image automatically from the new `site_logo` theme option, or Yoast SEO settings.

**Comment by robneu** [comment]
I haven't really looked into this at all, but If they're requiring it for the FoodEstablishment type it's probably only a matter of time before it becomes a requirement for all local business schemas.

You probably should just add the ability to add an image in the plugin rather than depending on a theme option or Yoast. 

It might be good to try to pull the image from there when first loading it so that people don't need to set it twice, but since both of those are optional and adoption is pretty slow on the `site_logo` I think you're going to need your own value for it.

**Comment by NateWr** [comment]
:+1:

**Comment by NateWr** [comment]
Additional fields are now recommended: `priceRange` and `servesCuisine` (for FoodEstablishment types).

**Comment by NateWr** [comment]
Image now supported. The additional restaurant-related fields are filed at: https://github.com/NateWr/food-and-drink-menu/issues/32
